### ISSUE TITLE
Clone Projects

### ISSUE THREAD

**Issue by walkman04** [notime-streaming/notime-feature-requests-and-bugs#15]
At present time there is no option to to simply clone an entire project. In order to create for instance one private and a coroparte set of scenes it would be useful to easily clone the existing scene set. This could also be useful for testing purposes by simply modifying scenes in a "Test" scene scenario, w/o "destroying the "master" screen set. 

In a second step it would also be useful to copy/move scenes from one scene set to another.

**Comment by mathias-ewald** [comment]
I am not sure what you mean by "screen set". 
- A user can have multiple projects
- A projects consists of multiples Scenes and Transitions

Do you wish to be able to clone Projects?
