### ISSUE TITLE
DSK Pre-Multiplied Alpha 

### ISSUE THREAD

**Issue by walkman04** [notime-streaming/notime-feature-requests-and-bugs#22]
In a given scene it should be possible to activate DSK in order to show a "bug" on the screen. Notime allows to activate the DSK and the selection of the desired still as well as Media slot.  To show the bug properly (full alpha transparancy) the Pre-Multiplied Alpha feature needs to be actived. This is currently not possible.

**Comment by walkman04** [comment]
In order do display an pre-multiplied alpha cannel correct Notime needs to use the Key Source correctly. At present time the Key Source is not using Media Player 2 Key setting.

**Comment by mathias-ewald** [comment]
I will keep the missing support for premulitplied key configuration in this issue. The key source is a separate bug.
