### ISSUE TITLE
Up-/Downstream Key needs to deactivated before switching to a new scene

### ISSUE THREAD

**Issue by walkman04** [notime-streaming/notime-feature-requests-and-bugs#23]
If a given Key is on air. Notime needs to deactivate all Keys that are on air befire switching to a new scene. Otherwise an activated key can lead to unwanted results.

**Comment by mathias-ewald** [comment]
USKs are a bit tricky to handle correctly but afaik notime does it correctly. For DSKs, I am not sure. Can you provide the exact situation, back that up with generated macros and document that here please?
